# Netlify configuration file

# 1. Build Settings
[build]
  # This command tells Netlify to build your app for production
  command = "ng build --configuration production"

  # This is the folder that Angular builds your site into.
  # IMPORTANT: You MUST verify this path.
  publish = "/dist/admin-dashboard"

# 2. Redirects for Angular Routing (Fixes 404 Errors)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
